// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import type {
  Encyclopedia_GetCommunicationQueryRequest,
  CampusLifeData_tradeHistoryQueryRequest,
  User_loginBodyRequest,
  User_loginHeaderRequest,
  User_myInfoCookieRequest,
  User_logoutCookieRequest,
  User_userInfoQueryRequest,
  User_userInfoCookieRequest,
} from './namespaces';

export default class Tongji_pobyService<T> {
  private request: any = () => {
    throw new Error('Tongji_pobyService.request is undefined');
  };
  private baseURL: string | ((path: string) => string) = '';

  constructor(options?: {
    baseURL?: string | ((path: string) => string);
    request?<R>(
      params: {
        url: string;
        method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
        data?: any;
        params?: any;
        headers?: any;
      },
      options?: T,
    ): Promise<R>;
  }) {
    this.request = options?.request || this.request;
    this.baseURL = options?.baseURL || this.baseURL;
  }

  private genBaseURL(path: string) {
    if (typeof this.baseURL === 'string') {
      const baseUrl = this.baseURL.trim().replace(/\/+$/, '');
      const apiPath = path.trim().replace(/^\/+/, '');
      return baseUrl + '/' + apiPath;
    }
    return this.baseURL(path);
  }

  /* API Services */

  /** 日程-查找个人所有日程 */
  DailyPlan_AllGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/daily-plan/getAllDailyPlan');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 日程-查找单个日程 */
  Dailyplan_SingleGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/daily-plan/getSingleDailyPlan');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 校园卡余额 */
  CampusLifeData_cardBalanceGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusLifeData/cardBalance');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 今日消费 */
  CampusLifeData_todayConsumptionGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusLifeData/todayConsumption');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 昨日消费 */
  CampusLifeData_yesterdayConsumptionGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusLifeData/yesterdayConsumption');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 月度平均消费 */
  CampusLifeData_monthAverageConsumptionGET(
    req?: any,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusLifeData/monthAverageConsumption');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 搜索校内通讯录zoneId, keyword, pageNo, pageNo */
  Encyclopedia_GetCommunicationGET(
    req: Encyclopedia_GetCommunicationQueryRequest,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/encyclopedia/encyclopediaGetCommunication');
    const method = 'GET';
    const data = undefined;
    const params = {
      zoneId: _req['zoneId'],
      keyword: _req['keyword'],
      pageNo: _req['pageNo'],
      pageSize: _req['pageSize'],
    };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 用户年度基本数据 */
  CampusAnnualReport2025_basicGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusAnnualReport2025/user/basic');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 交易流水记录 */
  CampusLifeData_tradeHistoryGET(
    req: CampusLifeData_tradeHistoryQueryRequest,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusLifeData/tradeHistory');
    const method = 'GET';
    const data = undefined;
    const params = { yearMonth: _req['yearMonth'] };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 年度考试数据 */
  CampusAnnualReport2025_examGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusAnnualReport2025/exam');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 年度用户画像 */
  CampusAnnualReport2025_personaGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusAnnualReport2025/persona');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 入校次数统计 */
  CampusAnnualReport2025_accessschoolGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusAnnualReport2025/access/school');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 图书借阅统计 */
  CampusAnnualReport2025_libraryborrowGET(
    req?: any,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusAnnualReport2025/library/borrow');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 图书馆入馆统计 */
  CampusAnnualReport2025_libraryaccessGET(
    req?: any,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusAnnualReport2025/library/access');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 年度学习数据（课程数、GPA等） */
  CampusAnnualReport2025_studyGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusAnnualReport2025/study');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 	食堂消费统计 */
  CampusAnnualReport2025_consumptionGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusAnnualReport2025/consumption');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 用户登录 */
  User_loginGET(
    req: User_loginBodyRequest & User_loginHeaderRequest,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/user/login');
    const method = 'GET';
    const data = { user: _req['user'] };
    const params = undefined;
    const headers = { 'Content-Type': _req['Content-Type'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 获取当前用户信息 */
  User_myInfoGET(req: User_myInfoCookieRequest, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/user/myInfo');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 退出登录 */
  User_logoutGET(req: User_logoutCookieRequest, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/user/logout');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 按 ID 查用户信息 */
  User_userInfoGET(
    req: User_userInfoQueryRequest & User_userInfoCookieRequest,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/user/userInfo ');
    const method = 'GET';
    const data = undefined;
    const params = { userId: _req['userId'] };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 当月总消费 */
  CampusLifeData_monthTotalConsumptionGET(
    req?: any,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/campusLifeData/monthTotalConsumption');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }
}
