// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export interface CallMcpBodyRequest {
  /** 本 CAM 接口统一使用整数 JSON-RPC 请求 ID，响应与请求对应；不是订单编号。MCP 本身也允许字符串 ID，本契约不使用该形式。 */
  id: number;
  jsonrpc: string;
  method: string;
  params: CallMcpBodyRequestParams;
}

export interface CallMcpBodyRequestParams {
  /** CAM 兼容参数全集。只传当前工具接受的字段，不要把所有可选字段都发送。各工具必填字段：queryShopList: longitude, latitude；searchProductForMcp: deptId, query；switchProduct: deptId, productId, skuCode, attrOperationParam, amount；queryProductDetailInfo: deptId, productId；previewOrder: deptId, productList；createOrder: deptId, productList, longitude, latitude；queryOrderDetailInfo: orderId；cancelOrder: orderId。独立的 *Arguments Schema 保留精确约束，调用层按工具名校验。 */
  arguments?: CallMcpBodyRequestParamsArguments;
  /** 仅 tools/list 可用，取上一页 nextCursor。 */
  cursor?: string;
  name?: string;
}

export interface CallMcpBodyRequestParamsArguments {
  /** 商品数量 */
  amount?: number;
  /** 商品属性切换参数 */
  attrOperationParam?: CallMcpBodyRequestParamsArgumentsAttrOperationParam;
  /** 优惠券列表，此参数来自 `previewOrder` 的返回字段 `couponCodeList` */
  couponCodeList?: string[];
  /** 门店id */
  deptId?: number;
  /** 门店名称 */
  deptName?: string;
  /** 纬度 */
  latitude?: number;
  /** 经度 */
  longitude?: number;
  /** 订单ID */
  orderId?: string;
  /** 商品ID */
  productId?: number;
  /** 订单商品列表 */
  productList?: CallMcpBodyRequestParamsArgumentsProductListItem[];
  /** 用户原始查询文本 */
  query?: string;
  /** 订单备注 */
  remark?: string;
  /** 商品SKU编码 */
  skuCode?: string;
}

export interface CallMcpBodyRequestParamsArgumentsAttrOperationParam {
  attributeId: number;
  subAttr: CallMcpBodyRequestParamsArgumentsAttrOperationParamSubAttr;
}

export interface CallMcpBodyRequestParamsArgumentsAttrOperationParamSubAttr {
  attributeId: number;
  operation: number;
}

export interface CallMcpBodyRequestParamsArgumentsProductListItem {
  amount: number;
  productId: number;
  skuCode: string;
}

export interface CallMcp200Response {
  error?: CallMcp200ResponseError;
  id: number | null;
  jsonrpc: string;
  /** ping 成功为空对象；tools/list 使用 tools/nextCursor；tools/call 使用 content/structuredContent/isError。 */
  result?: CallMcp200ResponseResult;
}

export interface CallMcp200ResponseError {
  code: number;
  data?: string;
  message: string;
}

export interface CallMcp200ResponseResult {
  _meta?: any;
  content?: CallMcp200ResponseResultContentItem[];
  /** true 表示工具执行失败，即使 HTTP 为 200。 */
  isError?: boolean;
  nextCursor?: string;
  structuredContent?: any;
  tools?: CallMcp200ResponseResultToolsItem[];
}

export interface CallMcp200ResponseResultContentItem {
  /** type=text 时存在；业务数据可能编码为 JSON 字符串。 */
  text?: string;
  /** 通常为 text；其他 MCP 内容类型原样保留。 */
  type: string;
}

export interface CallMcp200ResponseResultToolsItem {
  description?: string;
  inputSchema: any;
  name: string;
  outputSchema?: any;
}
