import { z } from "zod";

export const Postgraduate_score200ResponseDataListItemSchema = z.object({
    addScore: z.string().nullish().describe("附加成绩（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    calendar: z.string().nullish().describe("学期信息（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    calendarId: z.number().nullish().describe("学期编号（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    courseCode: z.string().nullish().describe("课程代码（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    courseCredit: z.string().nullish().describe("学分（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    courseLabel: z.string().nullish().describe("课程分类（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    courseLabelId: z.string().nullish().describe("分类标识（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    courseLabelName: z.string().nullish().describe("分类名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    courseName: z.string().nullish().describe("课程名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    courseNameEn: z.string().nullish().describe("课程英文名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    courseNature: z.string().nullish().describe("课程性质（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    courseNatureI18n: z.string().nullish().describe("课程性质显示名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    courseNum: z.string().nullish().describe("课程编号（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    createAt: z.string().nullish().describe("创建时间（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    credit: z.number().nullish().describe("学分（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    dailyScore: z.union([z.string(), z.null()]).nullish().describe("平时成绩（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    enterPerson: z.string().nullish().describe("成绩录入人（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    enterTime: z.string().nullish().describe("成绩录入时间（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    examMode: z.string().nullish().describe("考试方式（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    examModeI18n: z.string().nullish().describe("考试方式显示名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    examScore1: z.string().nullish().describe("考试成绩一（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    examScore2: z.string().nullish().describe("考试成绩二（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    examScoreName1: z.string().nullish().describe("考试成绩一名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    examScoreName2: z.string().nullish().describe("考试成绩二名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    examType: z.string().nullish().describe("考试类型（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    examTypeI18n: z.string().nullish().describe("考试类型显示名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    faculty: z.string().nullish().describe("院系信息（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    facultyI18n: z.string().nullish().describe("院系显示名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    finalScore: z.union([z.string(), z.null()]).nullish().describe("最终成绩（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    formLearning: z.string().nullish().describe("学习形式（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    formLearningI18n: z.string().nullish().describe("学习形式显示名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    greadePoint: z.string().nullish().describe("绩点（上游字段拼写为 greadePoint）（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    huxuan: z.string().nullish().describe("互选标识（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    id: z.string().nullish().describe("记录标识（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    isDegreeCourse: z.string().nullish().describe("是否学位课程（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    isElcCourse: z.string().nullish().describe("选课标识（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    isPass: z.number().nullish().describe("是否通过（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    isPassCn: z.string().nullish().describe("是否通过的中文说明（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    isShow: z.string().nullish().describe("是否展示（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    learnType: z.string().nullish().describe("修读类型（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    learnTypeI18n: z.string().nullish().describe("修读类型显示名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    makeupScore: z.string().nullish().describe("补考成绩（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    managerDeptId: z.string().nullish().describe("管理部门标识（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    midtermExamType: z.string().nullish().describe("期中考试类型（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    midtermScore: z.union([z.string(), z.null()]).nullish().describe("期中成绩（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    newCourseCode: z.string().nullish().describe("新课程代码（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    newCourseNum: z.string().nullish().describe("新课程编号（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    period: z.string().nullish().describe("学时（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    projId: z.string().nullish().describe("项目标识（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    recoredType: z.string().nullish().describe("记录类型（沿用上游拼写）（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    recoredTypeI18n: z.string().nullish().describe("记录类型显示名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    releaseAt: z.string().nullish().describe("发布时间（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    releaseType: z.string().nullish().describe("发布类型（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    remark: z.string().nullish().describe("备注（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    remarkPk: z.string().nullish().describe("排课备注（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    scoreSource: z.string().nullish().describe("成绩来源（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    scoreTypeList: z.string().nullish().describe("成绩类型列表（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    showAt: z.string().nullish().describe("展示时间（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    slowScore: z.string().nullish().describe("缓考成绩（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    specialScore: z.string().nullish().describe("特殊成绩（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    standardScore: z.string().nullish().describe("标准成绩（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    studentName: z.string().nullish().describe("学生姓名（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    teacherId: z.string().nullish().describe("教师工号（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    teacherName: z.string().nullish().describe("教师姓名（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    teachingClassId: z.number().nullish().describe("教学班标识（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    teachingClassIdNew: z.string().nullish().describe("新教学班标识（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    teachingClassName: z.string().nullish().describe("教学班名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    totalMarkScore: z.string().nullish().describe("总评成绩（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    trainingLevel: z.string().nullish().describe("培养层次（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    trainingLevelI18n: z.string().nullish().describe("培养层次显示名称（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    updateTime: z.string().nullish().describe("更新时间（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
});

export const Postgraduate_score200ResponseDataSchema = z.object({
    size: z.number().nullish().describe("当前页记录数（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    endRow: z.number().nullish().describe("末行位置（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    firstPage: z.number().nullish().describe("首页页码（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    hasNextPage: z.boolean().nullish().describe("是否有下一页（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    hasPreviousPage: z.boolean().nullish().describe("是否有上一页（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    isFirstPage: z.boolean().nullish().describe("是否首页（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    isLastPage: z.boolean().nullish().describe("是否末页（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    lastPage: z.number().nullish().describe("末页页码（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    list: z.array(Postgraduate_score200ResponseDataListItemSchema).nullish().describe("业务记录列表。"),
    navigateFirstPage: z.number().nullish().describe("导航起始页（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    navigateLastPage: z.number().nullish().describe("导航结束页（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    navigatePages: z.number().nullish().describe("导航页数量（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    navigatepageNums: z.array(z.number()).nullish().describe("导航页码列表（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    nextPage: z.number().nullish().describe("下一页页码（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    pageNum: z.number().nullish().describe("当前页码（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    pageSize: z.number().nullish().describe("每页记录数（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    pages: z.number().nullish().describe("总页数（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    prePage: z.number().nullish().describe("上一页页码（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    startRow: z.number().nullish().describe("起始行位置（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    total: z.number().nullish().describe("记录总数（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
});
