import { z } from "zod";

export const Postgraduate_score200ResponseDataListItemSchema = z.object({
    addScore: z.string().nullish(),
    calendar: z.string().nullish(),
    calendarId: z.number().nullish(),
    courseCode: z.string().nullish(),
    courseCredit: z.string().nullish(),
    courseLabel: z.string().nullish(),
    courseLabelId: z.string().nullish(),
    courseLabelName: z.string().nullish(),
    courseName: z.string().nullish(),
    courseNameEn: z.string().nullish(),
    courseNature: z.string().nullish(),
    courseNatureI18n: z.string().nullish(),
    courseNum: z.string().nullish(),
    createAt: z.string().nullish(),
    credit: z.number().nullish(),
    dailyScore: z.union([z.string(), z.null()]).nullish(),
    enterPerson: z.string().nullish(),
    enterTime: z.string().nullish(),
    examMode: z.string().nullish(),
    examModeI18n: z.string().nullish(),
    examScore1: z.string().nullish(),
    examScore2: z.string().nullish(),
    examScoreName1: z.string().nullish(),
    examScoreName2: z.string().nullish(),
    examType: z.string().nullish(),
    examTypeI18n: z.string().nullish(),
    faculty: z.string().nullish(),
    facultyI18n: z.string().nullish(),
    finalScore: z.union([z.string(), z.null()]).nullish(),
    formLearning: z.string().nullish(),
    formLearningI18n: z.string().nullish(),
    greadePoint: z.string().nullish(),
    huxuan: z.string().nullish(),
    id: z.string().nullish(),
    isDegreeCourse: z.string().nullish(),
    isElcCourse: z.string().nullish(),
    isPass: z.number().nullish(),
    isPassCn: z.string().nullish(),
    isShow: z.string().nullish(),
    learnType: z.string().nullish(),
    learnTypeI18n: z.string().nullish(),
    makeupScore: z.string().nullish(),
    managerDeptId: z.string().nullish(),
    midtermExamType: z.string().nullish(),
    midtermScore: z.union([z.string(), z.null()]).nullish(),
    newCourseCode: z.string().nullish(),
    newCourseNum: z.string().nullish(),
    period: z.string().nullish(),
    projId: z.string().nullish(),
    recoredType: z.string().nullish(),
    recoredTypeI18n: z.string().nullish(),
    releaseAt: z.string().nullish(),
    releaseType: z.string().nullish(),
    remark: z.string().nullish(),
    remarkPk: z.string().nullish(),
    scoreSource: z.string().nullish(),
    scoreTypeList: z.string().nullish(),
    showAt: z.string().nullish(),
    slowScore: z.string().nullish(),
    specialScore: z.string().nullish(),
    standardScore: z.string().nullish(),
    studentName: z.string().nullish(),
    teacherId: z.string().nullish(),
    teacherName: z.string().nullish(),
    teachingClassId: z.number().nullish(),
    teachingClassIdNew: z.string().nullish(),
    teachingClassName: z.string().nullish(),
    totalMarkScore: z.string().nullish(),
    trainingLevel: z.string().nullish(),
    trainingLevelI18n: z.string().nullish(),
    updateTime: z.string().nullish(),
});

export const Postgraduate_score200ResponseDataSchema = z.object({
    size: z.number().nullish(),
    endRow: z.number().nullish(),
    firstPage: z.number().nullish(),
    hasNextPage: z.boolean().nullish(),
    hasPreviousPage: z.boolean().nullish(),
    isFirstPage: z.boolean().nullish(),
    isLastPage: z.boolean().nullish(),
    lastPage: z.number().nullish(),
    list: z.array(Postgraduate_score200ResponseDataListItemSchema).nullish(),
    navigateFirstPage: z.number().nullish(),
    navigateLastPage: z.number().nullish(),
    navigatePages: z.number().nullish(),
    navigatepageNums: z.array(z.number()).nullish(),
    nextPage: z.number().nullish(),
    pageNum: z.number().nullish(),
    pageSize: z.number().nullish(),
    pages: z.number().nullish(),
    prePage: z.number().nullish(),
    startRow: z.number().nullish(),
    total: z.number().nullish(),
});
