import { z } from "zod";

export const Get_final_exam_info200ResponseDataItemSchema = z.object({
    applyStatus: z.union([z.string(), z.null()]).nullish().describe("审核状态，期末考该字段为空"),
    assessmentMode: z.string().nullish().describe("考核方式 1考试/2考查"),
    calendarId: z.number().nullish().describe("学期编号（依据字段名及返回示例解释；官网未明确说明，具体单位和枚举以接口为准。）"),
    classCalendarId: z.number().nullish().describe("课程所在学期"),
    college: z.string().nullish().describe("开课学院"),
    courseCode: z.string().nullish().describe("课程代码"),
    courseName: z.string().nullish().describe("课程名称"),
    defect: z.union([z.number(), z.null()]).nullish().describe("是否缺考 1 是 0 否"),
    deptCode: z.string().nullish().describe("学院"),
    examCalendarId: z.number().nullish().describe("考试学期"),
    examDate: z.union([z.string(), z.null()]).nullish().describe("排考具体日期"),
    examEndTime: z.union([z.string(), z.null()]).nullish().describe("结束时间"),
    examInfoId: z.union([z.number(), z.null()]).nullish().describe("本科排考管理表ID"),
    examRoomId: z.union([z.number(), z.null()]).nullish().describe("本科学生排考表 本科排考教室ID"),
    examSituation: z.union([z.number(), z.null()]).nullish().describe("考试情况 1 正常 2 缓考 3无资格 4免试"),
    examStartTime: z.union([z.string(), z.null()]).nullish().describe("开始时间"),
    examStatus: z.number().nullish().describe("排考状态 1 排考时间未排考考场 2 时间考场"),
    examStudentId: z.union([z.number(), z.null()]).nullish().describe("本科学生排考表ID"),
    examTime: z.union([z.string(), z.null()]).nullish().describe("考试时间"),
    examType: z.union([z.number(), z.null()]).nullish().describe("考试类型 1 期末考试 2 补缓考"),
    grade: z.number().nullish().describe("年级（本科：当前年级；研究生：年级）"),
    major: z.string().nullish().describe("专业代码"),
    major2: z.union([z.string(), z.null()]).nullish().describe("专业2代码"),
    managementCollege2Code: z.union([z.string(), z.null()]).nullish().describe("学院2"),
    name: z.string().nullish().describe("姓名"),
    reExamRemark: z.union([z.string(), z.null()]).nullish().describe("缓考备注 期末考该字段为空"),
    remark: z.union([z.string(), z.null()]).nullish().describe("本科排考管理表 备注"),
    roomId: z.union([z.number(), z.null()]).nullish().describe("考场代码"),
    roomName: z.union([z.string(), z.null()]).nullish().describe("考场名称"),
    teacherStr: z.string().nullish().describe("任课教师，格式为：姓名（工号），姓名（工号），姓名（工号）"),
    teachingClassCode: z.string().nullish().describe("课程序号"),
    teachingClassId: z.number().nullish().describe("教学班表ID"),
    weekDay: z.union([z.number(), z.null()]).nullish().describe("星期几"),
    weekNumber: z.union([z.number(), z.null()]).nullish().describe("第几周"),
});
