import { z } from "zod";

export const Get_final_exam_info200ResponseDataItemSchema = z.object({
    applyStatus: z.union([z.string(), z.null()]).nullish(),
    assessmentMode: z.string().nullish(),
    calendarId: z.number().nullish(),
    classCalendarId: z.number().nullish(),
    college: z.string().nullish(),
    courseCode: z.string().nullish(),
    courseName: z.string().nullish(),
    defect: z.union([z.number(), z.null()]).nullish(),
    deptCode: z.string().nullish(),
    examCalendarId: z.number().nullish(),
    examDate: z.union([z.string(), z.null()]).nullish(),
    examEndTime: z.union([z.string(), z.null()]).nullish(),
    examInfoId: z.union([z.number(), z.null()]).nullish(),
    examRoomId: z.union([z.number(), z.null()]).nullish(),
    examSituation: z.union([z.number(), z.null()]).nullish(),
    examStartTime: z.union([z.string(), z.null()]).nullish(),
    examStatus: z.number().nullish(),
    examStudentId: z.union([z.number(), z.null()]).nullish(),
    examTime: z.union([z.string(), z.null()]).nullish(),
    examType: z.union([z.number(), z.null()]).nullish(),
    grade: z.number().nullish(),
    major: z.string().nullish(),
    major2: z.union([z.string(), z.null()]).nullish(),
    managementCollege2Code: z.union([z.string(), z.null()]).nullish(),
    name: z.string().nullish(),
    reExamRemark: z.union([z.string(), z.null()]).nullish(),
    remark: z.union([z.string(), z.null()]).nullish(),
    roomId: z.union([z.number(), z.null()]).nullish(),
    roomName: z.union([z.string(), z.null()]).nullish(),
    teacherStr: z.string().nullish(),
    teachingClassCode: z.string().nullish(),
    teachingClassId: z.number().nullish(),
    weekDay: z.union([z.number(), z.null()]).nullish(),
    weekNumber: z.union([z.number(), z.null()]).nullish(),
});
