// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import type {
  CoursesQueryRequest,
  Courses200Response,
  Calendars_detailsPathRequest,
  GetAllCalendar200Response,
  FindGradeByCalendarIdBodyRequest,
  FindGradeByCalendarId200Response,
  CourseDetailPathRequest,
  CourseDetail200Response,
  CourseidRelatedPathRequest,
  FindMajorByGradeBodyRequest,
  FindMajorByGrade200Response,
} from './namespaces';

export default class YourtjService<T> {
  private request: any = () => {
    throw new Error('YourtjService.request is undefined');
  };
  private baseURL: string | ((path: string) => string) = '';

  constructor(options?: {
    baseURL?: string | ((path: string) => string);
    request?<R>(
      params: {
        url: string;
        method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
        data?: any;
        params?: any;
        headers?: any;
      },
      options?: T,
    ): Promise<R>;
  }) {
    this.request = options?.request || this.request;
    this.baseURL = options?.baseURL || this.baseURL;
  }

  private genBaseURL(path: string) {
    if (typeof this.baseURL === 'string') {
      const baseUrl = this.baseURL.trim().replace(/\/+$/, '');
      const apiPath = path.trim().replace(/^\/+/, '');
      return baseUrl + '/' + apiPath;
    }
    return this.baseURL(path);
  }

  /* API Services */

  /** 获取课程列表 */
  CoursesGET(
    req: CoursesQueryRequest,
    options?: T,
  ): Promise<Courses200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/api/courses');
    const method = 'GET';
    const data = undefined;
    const params = {
      page: _req['page'],
      limit: _req['limit'],
      q: _req['q'],
      includeTotal: _req['includeTotal'],
    };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 获取所有学期列表 */
  GetAllCalendarGET(
    req?: any,
    options?: T,
  ): Promise<GetAllCalendar200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/api/getAllCalendar');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 获取当前学期所有年级 */
  FindGradeByCalendarIdPOST(
    req: FindGradeByCalendarIdBodyRequest,
    options?: T,
  ): Promise<FindGradeByCalendarId200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/api/findGradeByCalendarId');
    const method = 'POST';
    const data = { calendarId: _req['calendarId'] };
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 获取课程详情 */
  CourseDetailGET(
    req: CourseDetailPathRequest,
    options?: T,
  ): Promise<CourseDetail200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/api/course/{id}');
    if (_req['id'] !== undefined && _req['id'] !== null) {
      url = url.replace('{id}', String(_req['id']));
    }
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 获取关联课程 */
  CourseidRelatedGET(
    req: CourseidRelatedPathRequest,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/api/course/{id}/related');
    if (_req['id'] !== undefined && _req['id'] !== null) {
      url = url.replace('{id}', String(_req['id']));
    }
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 根据学期和年级获取当年份全部专业 */
  FindMajorByGradePOST(
    req: FindMajorByGradeBodyRequest,
    options?: T,
  ): Promise<FindMajorByGrade200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/api/findMajorByGrade');
    const method = 'POST';
    const data = { calendarId: _req['calendarId'], grade: _req['grade'] };
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }
}
