// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import type {
  CourseReviewListQueryRequest,
  CourseReviewListPathRequest,
  CourseReviewList200Response,
  CourseDetailGetPathRequest,
  CourseDetailGet200Response,
  CourseDetailGet400Response,
  CourseSearchQueryRequest,
  CourseSearch200Response,
  GetAllCalendar200Response,
  FindGradeByCalendarIdBodyRequest,
  FindGradeByCalendarId200Response,
  FindMajorByGradeBodyRequest,
  FindMajorByGrade200Response,
  CourseRelatedListPathRequest,
  CourseRelatedList200Response,
  CourseRelatedList400Response,
} from './namespaces';

export default class YourtjService<T> {
  private request: any = () => {
    throw new Error('YourtjService.request is undefined');
  };
  private baseURL: string | ((path: string) => string) = '';

  constructor(options?: {
    baseURL?: string | ((path: string) => string);
    request?<R>(
      params: {
        url: string;
        method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
        data?: any;
        params?: any;
        headers?: any;
      },
      options?: T,
    ): Promise<R>;
  }) {
    this.request = options?.request || this.request;
    this.baseURL = options?.baseURL || this.baseURL;
  }

  private genBaseURL(path: string) {
    if (typeof this.baseURL === 'string') {
      const baseUrl = this.baseURL.trim().replace(/\/+$/, '');
      const apiPath = path.trim().replace(/^\/+/, '');
      return baseUrl + '/' + apiPath;
    }
    return this.baseURL(path);
  }

  /* API Services */

  /** 获取指定课程的评价列表，包含评价正文、HTML、评分、作者展示信息、赞踩数量和时间。支持按开课记录筛选，并通过不透明游标分页；返回下一页游标和评价总数。 */
  CourseReviewListGET(
    req: CourseReviewListQueryRequest & CourseReviewListPathRequest,
    options?: T,
  ): Promise<CourseReviewList200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/api/forum/courses/{courseId}/reviews');
    if (_req['courseId'] !== undefined && _req['courseId'] !== null) {
      url = url.replace('{courseId}', String(_req['courseId']));
    }
    const method = 'GET';
    const data = undefined;
    const params = {
      offeringId: _req['offeringId'],
      cursor: _req['cursor'],
      pageSize: _req['pageSize'],
    };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 获取指定课程的名称、代码、教师、院系、学分、开课记录及评分统计；不包含评价正文 */
  CourseDetailGetGET(
    req: CourseDetailGetPathRequest,
    options?: T,
  ): Promise<CourseDetailGet200Response & CourseDetailGet400Response> {
    const _req = req || {};
    let url = this.genBaseURL('/api/forum/courses/{courseId}');
    if (_req['courseId'] !== undefined && _req['courseId'] !== null) {
      url = url.replace('{courseId}', String(_req['courseId']));
    }
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 按关键词、教师、院系、学期和校区查询课程，支持仅查看有评价的课程及按评分排序 */
  CourseSearchGET(
    req: CourseSearchQueryRequest,
    options?: T,
  ): Promise<CourseSearch200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/api/forum/courses');
    const method = 'GET';
    const data = undefined;
    const params = {
      keyword: _req['keyword'],
      instructor: _req['instructor'],
      department: _req['department'],
      term: _req['term'],
      campus: _req['campus'],
      onlyWithReviews: _req['onlyWithReviews'],
      sortBy: _req['sortBy'],
      page: _req['page'],
      size: _req['size'],
    };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 查询课程评价的 AI 总结状态及已有总结，包含推荐倾向、关键词、优点、缺点、生成时间和模型 */
  CourseSummaryGetGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/api/forum/courses/{courseId}/summary');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 获取所有学期列表 */
  GetAllCalendarGET(
    req?: any,
    options?: T,
  ): Promise<GetAllCalendar200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/api/getAllCalendar');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 获取当前学期所有年级 */
  FindGradeByCalendarIdPOST(
    req: FindGradeByCalendarIdBodyRequest,
    options?: T,
  ): Promise<FindGradeByCalendarId200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/api/findGradeByCalendarId');
    const method = 'POST';
    const data = { calendarId: _req['calendarId'] };
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 根据学期和年级获取当年份全部专业 */
  FindMajorByGradePOST(
    req: FindMajorByGradeBodyRequest,
    options?: T,
  ): Promise<FindMajorByGrade200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/api/findMajorByGrade');
    const method = 'POST';
    const data = { calendarId: _req['calendarId'], grade: _req['grade'] };
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 获取指定课程的关联课程分组，包括相关教师的其他课程、同课程的其他教师记录，以及课程关联信息。关联课程 ID 可继续用于获取课程详情和评价。 */
  CourseRelatedListGET(
    req: CourseRelatedListPathRequest,
    options?: T,
  ): Promise<CourseRelatedList200Response & CourseRelatedList400Response> {
    const _req = req || {};
    let url = this.genBaseURL('/api/forum/courses/{courseId}/related');
    if (_req['courseId'] !== undefined && _req['courseId'] !== null) {
      url = url.replace('{courseId}', String(_req['courseId']));
    }
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }
}
