// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export interface CoursesQueryRequest {
  /** 页码 */
  page?: number;
  /** 每页条数 */
  limit?: number;
  /** 查询关键字，支持课程名、代码、教师 */
  q?: string;
  /** 返回值是否带 total、totalPages */
  includeTotal?: boolean;
}

export interface Courses200ResponseDataItem {
  /** 课程代码 */
  code: string;
  /** 学分 */
  credit: number;
  /** 开课学院 */
  department: string;
  id: number;
  is_legacy: number;
  name: string;
  /** 平均评价得分（满分 5.0） */
  rating: number;
  /** 评价数 */
  review_count: number;
  semester_names: string;
  /** 开课学期 */
  semesters: string[];
  teacher_name: string;
}

export interface Courses200Response {
  /** 本页最大条数 */
  limit: number;
  /** 当前页，从 1 开始 */
  page: number;
  /** 当前搜索条件总共条目数 */
  total?: number;
  /** 当前搜索条件总共页数 */
  totalPages?: number;
  /** 是否还有剩余页 */
  hasMore: boolean;
  /** course 数据 */
  data: Courses200ResponseDataItem[];
}

export interface GetAllCalendar200ResponseDataItem {
  calendarId: number;
  calendarName: string;
}

export interface GetAllCalendar200Response {
  code: number;
  msg: string;
  data: GetAllCalendar200ResponseDataItem[];
}

export interface FindGradeByCalendarIdBodyRequest {
  calendarId: number;
}

export interface FindGradeByCalendarId200ResponseData {
  gradeList: number[];
}

export interface FindGradeByCalendarId200Response {
  code: number;
  msg: string;
  data: FindGradeByCalendarId200ResponseData;
}

export interface CourseDetailPathRequest {
  /** 课程ID */
  id: number;
}

export interface CourseDetail200ResponseReviewsItem {
  approve_count: number;
  can_edit: boolean;
  comment: string;
  id: number;
  reviewer_name: string;
  score: string;
  semester: string;
  sqid: string;
  course_id: number;
  created_at: number;
  disapprove_count: number;
  is_hidden: number;
  is_icu: number;
  is_legacy: number;
  like_count: number;
  liked: boolean;
  rating: number;
  reviewer_avatar: string;
}

export interface CourseDetail200Response {
  code: string;
  credit: number;
  department: string;
  id: number;
  is_icu: number;
  is_legacy: number;
  name: string;
  review_avg: number;
  review_count: number;
  reviews: CourseDetail200ResponseReviewsItem[];
  search_keywords: string;
  semesters: string[];
  teacher_id: number;
  teacher_name: string;
}

export interface CourseidRelatedPathRequest {
  /** 课程ID */
  id: number;
}

export interface FindMajorByGradeBodyRequest {
  /** 学期 id */
  calendarId: number;
  /** 年级 */
  grade: number;
}

export interface FindMajorByGrade200ResponseDataItem {
  /** 专业代码 */
  code: string;
  /** 专业名 */
  name: string;
}

export interface FindMajorByGrade200Response {
  code: number;
  msg: string;
  data: FindMajorByGrade200ResponseDataItem[];
}
