// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import type {
  GetTokenBodyRequest,
  GetTokenQueryRequest,
  GetTokenCookieRequest,
  GetToken200Response,
  GetSMSCodeBodyRequest,
  GetSMSCodeQueryRequest,
  GetSMSCodeCookieRequest,
  GetSMSCode200Response,
  LoginBodyRequest,
  LoginQueryRequest,
  LoginCookieRequest,
  Login200Response,
} from './namespaces';

export default class LuckinCoffeeAuthService<T> {
  private request: any = () => {
    throw new Error('LuckinCoffeeAuthService.request is undefined');
  };
  private baseURL: string | ((path: string) => string) = '';

  constructor(options?: {
    baseURL?: string | ((path: string) => string);
    request?<R>(
      params: {
        url: string;
        method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
        data?: any;
        params?: any;
        headers?: any;
      },
      options?: T,
    ): Promise<R>;
  }) {
    this.request = options?.request || this.request;
    this.baseURL = options?.baseURL || this.baseURL;
  }

  private genBaseURL(path: string) {
    if (typeof this.baseURL === 'string') {
      const baseUrl = this.baseURL.trim().replace(/\/+$/, '');
      const apiPath = path.trim().replace(/^\/+/, '');
      return baseUrl + '/' + apiPath;
    }
    return this.baseURL(path);
  }

  /* API Services */

  /** Login 成功后调用。请求 Cookie 必须同时包含 csrfToken、LK_luckyopen_prod_CSID 和 LK_PROD_LUCKYOPEN_SSID，且 _csrf 与 csrfToken 相等。请求体 oauthApp 为 LUCKIN_MCP_AI。两枚身份 Cookie 使用 AND 关系，不能二选一。获取 Token 后可供瑞幸 MCP 的 Bearer 授权使用 */
  GetTokenPOST(
    req: GetTokenBodyRequest & GetTokenQueryRequest & GetTokenCookieRequest,
    options?: T,
  ): Promise<GetToken200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/capi/resource/m/oauth/mcp/getToken');
    const method = 'POST';
    const data = { oauthApp: _req['oauthApp'] };
    const params = { _csrf: _req['_csrf'] };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 无需 LK_luckyopen_prod_CSID、LK_PROD_LUCKYOPEN_SSID 或 Bearer 身份凭据。携带相同的 _csrf 与 csrfToken，提交手机号和 callCode。此接口只发送短信，响应不包含短信验证码；由用户收到短信后输入 Login.validateCode。 */
  GetSMSCodePOST(
    req: GetSMSCodeBodyRequest &
      GetSMSCodeQueryRequest &
      GetSMSCodeCookieRequest,
    options?: T,
  ): Promise<GetSMSCode200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/capi/resource/m/sys/base/validcode');
    const method = 'POST';
    const data = { callCode: _req['callCode'], mobile: _req['mobile'] };
    const params = { _csrf: _req['_csrf'] };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 无需预先提供两枚身份 Cookie。提交与发送短信时一致的手机号、countryNo、用户收到的 validateCode 和 type=1。已核实成功响应，登录成功响应通过两个独立 Set-Cookie 头设置 LK_luckyopen_prod_CSID 与 LK_PROD_LUCKYOPEN_SSID。客户端必须逐条解析并保存到同一用户的 Cookie jar。仅出现 CSID 不能证明登录成功：当前失败样本也设置了 CSID。 */
  LoginPOST(
    req: LoginBodyRequest & LoginQueryRequest & LoginCookieRequest,
    options?: T,
  ): Promise<Login200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/capi/resource/m/user/loginAi');
    const method = 'POST';
    const data = {
      countryNo: _req['countryNo'],
      mobile: _req['mobile'],
      type: _req['type'],
      validateCode: _req['validateCode'],
    };
    const params = { _csrf: _req['_csrf'] };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }
}
