// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export interface GetTokenQueryRequest {
  /** CSRF 值。根据用户已验证的流程，必须与本次请求 Cookie 中 csrfToken 完全一致；不要求固定为 1。示例 1 来自 Collection，不作为生产默认值。 */
  _csrf: string;
}

export interface GetTokenCookieRequest {
  /** CSRF Cookie，不是身份登录凭证。必须与查询参数 _csrf 完全一致。首次获取验证码及登录时也必须携带。 */
  csrfToken: string;
  /** Login 接口响应头 Set-Cookie 提供 */
  LK_luckyopen_prod_CSID: string;
  /** Login 接口响应头 Set-Cookie 提供 */
  LK_PROD_LUCKYOPEN_SSID: string;
}

export interface GetTokenBodyRequest {
  /** 当前瑞幸 MCP 应用标识。当前场景必须为 LUCKIN_MCP_AI。 */
  oauthApp: string;
}

export interface GetToken200Response {
  /** 成功业务码。 */
  busiCode: string;
  /** 成功结果码。 */
  code: number;
  content: GetToken200ResponseContent;
  /** 上游处理模块标识，已观察到 CLIENT、USER。 */
  handler?: string;
  /** 该接口成功样本中的登录状态。 */
  loginState?: number;
  /** 用户可读的业务提示。 */
  msg: string;
  /** 成功业务状态。 */
  status: string;
  /** 上游诊断标识；成功样本含身份及会话相关片段，不作为稳定用户 ID，不写入普通日志。 */
  uid?: string;
  /** 上游响应版本，样本值为 101。 */
  version?: string;
  /** 上游服务诊断标识。 */
  zeusId?: string;
}

export interface GetToken200ResponseContent {
  /** 瑞幸 MCP Bearer Token。后续放入 Authorization: Bearer <token>；不得写入日志、聊天历史或公开示例。 */
  luckyMcpToken: string;
  /** Token 时间字段。样本为 13 位整数，结合 Timeout 推测为到期 Unix 毫秒时间戳；单位和语义尚未由官方文档确认，集成时保留原值。 */
  luckyMcpTokenDate: number;
  /** Token 超时字段。结合日期字段推测为剩余有效秒数；单位及刷新规则尚待确认。 */
  luckyMcpTokenTimeout: number;
}

export interface GetSMSCodeQueryRequest {
  /** CSRF 值。根据用户已验证的流程，必须与本次请求 Cookie 中 csrfToken 完全一致；不要求固定为 1。示例 1 来自 Collection，不作为生产默认值。 */
  _csrf: string;
}

export interface GetSMSCodeCookieRequest {
  /** CSRF Cookie，不是身份登录凭证。必须与查询参数 _csrf 完全一致。首次获取验证码及登录时也必须携带。 */
  csrfToken: string;
}

export interface GetSMSCodeBodyRequest {
  /** 国家或地区电话区号；当前 Collection 使用 86。注意本接口字段名为 callCode。 */
  callCode: string;
  /** 接收短信的手机号，以字符串传递。示例为虚构号码。 */
  mobile: string;
}

export interface GetSMSCode200Response {
  /** 成功业务码。 */
  busiCode: string;
  /** 成功结果码。 */
  code: number;
  content: GetSMSCode200ResponseContent;
  /** 上游处理模块标识，已观察到 CLIENT、USER。 */
  handler?: string;
  /** 该接口成功样本中的登录状态。 */
  loginState?: number;
  /** 用户可读的业务提示。 */
  msg: string;
  /** 成功业务状态。 */
  status: string;
  /** 上游诊断标识；成功样本含身份及会话相关片段，不作为稳定用户 ID，不写入普通日志。 */
  uid?: string;
  /** 上游响应版本，样本值为 101。 */
  version?: string;
  /** 上游服务诊断标识。 */
  zeusId?: string;
}

export interface GetSMSCode200ResponseContent {
  /** 发送结果提示。 */
  msg: string;
  /** 发送成功样本值为 60；可能用于重发倒计时，其单位及精确语义尚未验证。 */
  remain: number;
  /** 上游返回的校验标志，成功样本为 false；不要将其当作业务成功判断。 */
  validate: boolean;
}

export interface LoginQueryRequest {
  /** CSRF 值。根据用户已验证的流程，必须与本次请求 Cookie 中 csrfToken 完全一致；不要求固定为 1。示例 1 来自 Collection，不作为生产默认值。 */
  _csrf: string;
}

export interface LoginCookieRequest {
  /** CSRF Cookie，不是身份登录凭证。必须与查询参数 _csrf 完全一致。首次获取验证码及登录时也必须携带。 */
  csrfToken: string;
}

export interface LoginBodyRequest {
  /** 国家或地区电话区号；与发送短信时 callCode 一致，本接口字段名为 countryNo。 */
  countryNo: string;
  /** 与 GetSMSCode 相同的手机号。 */
  mobile: string;
  /** 当前短信登录流程使用 1；其他值及含义未验证。 */
  type: number;
  /** 用户实际收到的短信验证码，保持字符串以保留前导零。示例不可用于登录。 */
  validateCode: string;
}

export interface Login200Response {
  /** 成功业务码。 */
  busiCode: string;
  /** 成功结果码。 */
  code: number;
  /** 依据实际成功响应建模；空字符串为合法样本值，字段可能随用户状态变化。 */
  content: Login200ResponseContent;
  /** 上游处理模块标识，已观察到 CLIENT、USER。 */
  handler?: string;
  /** 该接口成功样本中的登录状态。 */
  loginState?: number;
  /** 用户可读的业务提示。 */
  msg: string;
  /** 成功业务状态。 */
  status: string;
  /** 上游诊断标识；成功样本含身份及会话相关片段，不作为稳定用户 ID，不写入普通日志。 */
  uid?: string;
  /** 上游响应版本，样本值为 101。 */
  version?: string;
  /** 上游服务诊断标识。 */
  zeusId?: string;
}

export interface Login200ResponseContent {
  /** 小程序用户标识；样本为空字符串。 */
  appletUserId?: string;
  /** 上游授权字段；样本为空字符串，用途未验证。 */
  authCode?: string;
  /** 绑定检查信息；样本为空字符串。 */
  bindCheckInfo?: string;
  /** 绑定状态；样本为 0，枚举含义未验证。 */
  bindStatus?: number;
  /** 国家或地区电话区号；样本为 +86。 */
  countryZone?: string;
  /** 访客模式标志；样本为 false。 */
  guestMode?: boolean;
  /** 用户图片字段；样本为空字符串，不强制 URI 格式。 */
  imgUrl?: string;
  /** 手机号绑定标志；样本为 1。 */
  isBindPhone?: number;
  /** 脱敏手机号字段；样本为空字符串。 */
  maskingMobile?: string;
  /** 会员编号；样本为空字符串。 */
  memberNo?: string;
  /** 用户手机号，属于个人信息。 */
  mobile?: string;
  /** 用户信息载荷内的消息；样本为空字符串。 */
  msg?: string;
  /** 用户名称，属于个人信息。 */
  name?: string;
  /** 额外授权标志；样本为 0。 */
  needAuthorized?: number;
  /** 是否需要安全校验；样本为 false，true 的后续流程未覆盖。 */
  needSecurityVerify?: boolean;
  /** 新会员标志；样本为 0。 */
  newMember?: number;
  /** 上游 openid；样本为空字符串。 */
  openid?: string;
  /** 资料完善标志；样本为 false，完整语义未验证。 */
  perfect?: boolean;
  /** 电话号码字段；样本为空字符串。 */
  realPhoneNo?: string;
  /** 目前只观察到 null，非空类型及单位未验证，因此暂不限制类型。 */
  registerTime?: string;
  /** 会话密钥字段；样本为空字符串，不能代替响应 Cookie。 */
  sessionKey?: string;
  /** 性别编码；样本为 1，编码含义未验证。 */
  sex?: number;
  /** 用户状态编码；样本为 1，区别于顶层 status。 */
  status?: number;
  /** 提示信息；样本为空字符串。 */
  tipMsg?: string;
  /** 上游 unionid；样本为空字符串。 */
  unionid?: string;
  /** 瑞幸用户 ID，成功样本为字符串，保持字符串类型。 */
  userId?: string;
  /** 上游校验标志；成功样本为 false，不能作为登录成功条件。 */
  validate?: boolean;
}
