// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import type {
  CoursesQueryRequest,
  Course_idQueryRequest,
  Course_idPathRequest,
  Courseid_relatedQueryRequest,
  Courseid_relatedPathRequest,
  Calendars_id_coursesQueryRequest,
  Calendars_id_coursesPathRequest,
  Calendars_detailsPathRequest,
} from './namespaces';

export default class YourtjService<T> {
  private request: any = () => {
    throw new Error('YourtjService.request is undefined');
  };
  private baseURL: string | ((path: string) => string) = '';

  constructor(options?: {
    baseURL?: string | ((path: string) => string);
    request?<R>(
      params: {
        url: string;
        method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
        data?: any;
        params?: any;
        headers?: any;
      },
      options?: T,
    ): Promise<R>;
  }) {
    this.request = options?.request || this.request;
    this.baseURL = options?.baseURL || this.baseURL;
  }

  private genBaseURL(path: string) {
    if (typeof this.baseURL === 'string') {
      const baseUrl = this.baseURL.trim().replace(/\/+$/, '');
      const apiPath = path.trim().replace(/^\/+/, '');
      return baseUrl + '/' + apiPath;
    }
    return this.baseURL(path);
  }

  /* API Services */

  /** 获取课程列表 */
  CoursesGET(req: CoursesQueryRequest, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/api/courses');
    const method = 'GET';
    const data = undefined;
    const params = {
      clientId: _req['clientId'],
      page: _req['page'],
      limit: _req['limit'],
    };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 获取课程详情 */
  Course_idGET(
    req: Course_idQueryRequest & Course_idPathRequest,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/api/course/{id}');
    if (_req['id'] !== undefined && _req['id'] !== null) {
      url = url.replace('{id}', String(_req['id']));
    }
    const method = 'GET';
    const data = undefined;
    const params = { clientId: _req['clientId'] };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 获取关联课程 */
  Courseid_relatedGET(
    req: Courseid_relatedQueryRequest & Courseid_relatedPathRequest,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/api/course/{id}/related');
    if (_req['id'] !== undefined && _req['id'] !== null) {
      url = url.replace('{id}', String(_req['id']));
    }
    const method = 'GET';
    const data = undefined;
    const params = { clientId: _req['clientId'] };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 获取所有学期列表 */
  CalendarsGET(req?: any, options?: T): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/api/calendars');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 查询某学期的课程（按节次/年级专业/课程性质筛选） */
  Calendars_id_coursesGET(
    req: Calendars_id_coursesQueryRequest & Calendars_id_coursesPathRequest,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/api/calendars/{id}/courses');
    if (_req['id'] !== undefined && _req['id'] !== null) {
      url = url.replace('{id}', String(_req['id']));
    }
    const method = 'GET';
    const data = undefined;
    const params = { grade: _req['grade'], major: _req['major'] };
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 根据课程代码批量获取课程详情 */
  Calendars_detailsPOST(
    req: Calendars_detailsPathRequest,
    options?: T,
  ): Promise<any> {
    const _req = req || {};
    let url = this.genBaseURL('/api/calendars/{id}/courses/details');
    if (_req['id'] !== undefined && _req['id'] !== null) {
      url = url.replace('{id}', String(_req['id']));
    }
    const method = 'POST';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }
}
