// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export interface CoursesQueryRequest {
  /** 鉴权标识 */
  clientId: string;
  /** 页码 */
  page?: number;
  /** 每页条数 */
  limit?: number;
}

export interface Course_idQueryRequest {
  /** 鉴权标识 */
  clientId: string;
}

export interface Course_idPathRequest {
  /** 课程ID */
  id: number;
}

export interface Courseid_relatedQueryRequest {
  /** 鉴权标识 */
  clientId: string;
}

export interface Courseid_relatedPathRequest {
  /** 课程ID */
  id: number;
}

export interface Calendars_id_coursesQueryRequest {
  /** 入学年份 */
  grade: string;
  /** 专业名 */
  major: string;
}

export interface Calendars_id_coursesPathRequest {
  id: number;
}

export interface Calendars_detailsPathRequest {
  /** 学期 ID */
  id: number;
}
