// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export interface Encyclopedia_GetCommunicationQueryRequest {
  zoneId?: string;
  keyword?: string;
  pageNo?: number;
  pageSize?: number;
}

export interface CampusLifeData_tradeHistoryQueryRequest {
  yearMonth?: string;
}

export interface User_loginHeaderRequest {
  'Content-Type': string;
}

export interface User_loginBodyRequest {
  /** {"code": "wx.login()返回的code"} */
  user: any;
}

export interface User_myInfoHeaderRequest {
  /** 登录返回的 Session Cookie */
  Cookie: string;
}

export interface User_logoutHeaderRequest {
  /** 当前 Session Cookie */
  Cookie: string;
}

export interface User_userInfoQueryRequest {
  /** 目标用户 ID */
  userId: number;
}

export interface User_userInfoHeaderRequest {
  /** 当前 Session Cookie */
  Cookie: string;
}
